defaults: &defaults
  allow_dynamic_fields: false
  raise_not_found_error: false

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  port: 27017
  username: username
  password: password
  database: database
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
