defaults: &defaults
  allow_dynamic_fields: false
  raise_not_found_error: false

development:
  <<: *defaults
  host: localhost
  database: onelement_development

test:
  <<: *defaults
  host: localhost
  database: onelement_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  port: 27017
  username: rippleapp_chestermano
  password: H0rses4Courses
  database: rippleapp_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
